export { default as Home } from './home'
export { default as About } from './about'
export { default as Contact } from './contact'
export { default as Careers } from './careers'
export { default as Services } from './services'
export { default as Tracking } from './tracking'
export { default as Notfound }  from './404'